[package]
name = "otel-instrumentation-neo4jrs"
version = "0.1.0"
authors = ["Richard Peters <shadowrhyder@gmail.com>"]
license = "MIT"
edition = "2021"
description = "OpenTelemetry instrumentation for neo4rs Neo4j driver"
repository = "https://github.com/hermes-capital-io/hermes-platform"
keywords = ["neo4j", "opentelemetry", "tracing", "database", "graph"]

[badges]
maintenance = { status = "experimental" }

[features]
default = []

[dependencies]
neo4rs = "0.8.0"
tracing = "0.1.41"
opentelemetry = { version = "0.30.0", features = ["trace"] }
opentelemetry-semantic-conventions = "0.30.0"
futures-util = "0.3.31"

[dev-dependencies]
tokio = { version = "1.43.0", features = ["full", "test-util"] }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true